Migrate to K2, add Qodana
jetbrains-academy/kotlin-onboarding-collections pull request #69
Opened 2024-07-25 14:54 UTC by Daoortor

2024-07-30 18:31 UTC, mikrise2 requested changes
Some comments

2024-07-30 18:31 UTC, mikrise2 commented on .github/workflows/gradle-build-with-detekt.yml
> +on: [workflow_dispatch]
Here you have disabled the action execution on pull request or push, I'm not sure if this should be done. Especially I don't understand why **Detekt** won't run. In order to change the behavior of the action during execution, you need to change `jobs`.

2024-07-30 18:31 UTC, mikrise2 commented on .github/workflows/qodana.yml
> +          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
It looks very much like the file is almost entirely generated. It seems that we don't have branches that are specified in the config.... I suggest rewriting this file

2024-08-06 07:26 UTC, nbirillo requested changes
So as I can see in the merged PR you have not updated the compiled sources in the server resources, please do it. Also the workflow has not been run...

2024-08-19 07:40 UTC, merged